export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_AGE = 'CHANGE_AGE';
export const ADD_TWEET = 'ADD_TWEET';
export const FETCH_TWEET_STARTED = 'FETCH_TWEET_STARTED';
export const FETCH_TWEET_SUCCESS = 'FETCH_TWEET_SUCCESS';
export const FETCH_TWEET_FAILED = 'FETCH_TWEET_FAILED';